# Generated by Django 6.0.3 on 2026-03-24 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom')),
                ('message', models.TextField(verbose_name='Message')),
                ('note', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Note')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('publie', models.BooleanField(default=True, verbose_name='Publié')),
            ],
            options={
                'verbose_name': 'Avis',
                'verbose_name_plural': 'Avis',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('fichier', models.FileField(upload_to='documents/', verbose_name='Fichier')),
                ('type', models.CharField(choices=[('fiscal', 'Fiscal'), ('legal', 'Légal'), ('administratif', 'Administratif'), ('certification', 'Certification')], max_length=50, verbose_name='Type')),
                ('date_ajout', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-date_ajout'],
            },
        ),
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='Eau pour tous SARL', max_length=200, verbose_name='Nom')),
                ('slogan', models.CharField(blank=True, max_length=500, verbose_name='Slogan')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo/', verbose_name='Logo')),
                ('email', models.EmailField(max_length=200, verbose_name='Email')),
                ('telephone', models.CharField(max_length=50, verbose_name='Téléphone')),
                ('whatsapp', models.CharField(blank=True, max_length=50, verbose_name='WhatsApp')),
                ('adresse', models.TextField(default='Douala, Cameroun', verbose_name='Adresse')),
                ('description', models.TextField(verbose_name='Description')),
                ('zone_intervention', models.CharField(default='Tout le Cameroun', max_length=200, verbose_name="Zone d'intervention")),
                ('site_web', models.URLField(blank=True, verbose_name='Site web')),
                ('annees_experience', models.IntegerField(default=10, verbose_name="Années d'expérience")),
            ],
            options={
                'verbose_name': 'Entreprise',
                'verbose_name_plural': 'Entreprises',
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/', verbose_name='Image')),
                ('titre', models.CharField(blank=True, max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('type', models.CharField(choices=[('equipe', 'Équipe'), ('chantier', 'Chantier'), ('materiel', 'Matériel'), ('autre', 'Autre')], max_length=50, verbose_name='Type')),
                ('date_ajout', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
            ],
            options={
                'verbose_name': 'Média',
                'verbose_name_plural': 'Médias',
                'ordering': ['-date_ajout'],
            },
        ),
        migrations.CreateModel(
            name='Realisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('image_principale', models.ImageField(upload_to='realisations/', verbose_name='Image principale')),
                ('galerie', models.JSONField(blank=True, help_text="Liste des URLs d'images", null=True, verbose_name='Galerie')),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('termine', 'Terminé')], default='termine', max_length=20, verbose_name='Statut')),
                ('date_realisation', models.DateField(verbose_name='Date de réalisation')),
                ('localisation', models.CharField(blank=True, max_length=200, verbose_name='Localisation')),
                ('mise_en_avant', models.BooleanField(default=False, verbose_name='Mise en avant')),
            ],
            options={
                'verbose_name': 'Réalisation',
                'verbose_name_plural': 'Réalisations',
                'ordering': ['-date_realisation'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('icone', models.CharField(default='fas fa-tools', max_length=100, verbose_name='Icône (FontAwesome)')),
                ('ordre', models.IntegerField(default=0, verbose_name='Ordre')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['ordre', 'titre'],
            },
        ),
        migrations.CreateModel(
            name='Valeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('icone', models.CharField(max_length=100, verbose_name='Icône (FontAwesome)')),
                ('ordre', models.IntegerField(default=0, verbose_name='Ordre')),
            ],
            options={
                'verbose_name': 'Valeur',
                'verbose_name_plural': 'Valeurs',
                'ordering': ['ordre'],
            },
        ),
    ]
