# Generated by Django 6.0.3 on 2026-03-25 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eau', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='avis',
            name='message_en',
            field=models.TextField(null=True, verbose_name='Message'),
        ),
        migrations.AddField(
            model_name='avis',
            name='message_fr',
            field=models.TextField(null=True, verbose_name='Message'),
        ),
        migrations.AddField(
            model_name='document',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='document',
            name='description_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='document',
            name='titre_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Titre'),
        ),
        migrations.AddField(
            model_name='document',
            name='titre_fr',
            field=models.CharField(max_length=200, null=True, verbose_name='Titre'),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='adresse_en',
            field=models.TextField(default='Douala, Cameroun', null=True, verbose_name='Adresse'),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='adresse_fr',
            field=models.TextField(default='Douala, Cameroun', null=True, verbose_name='Adresse'),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='description_fr',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='slogan_en',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Slogan'),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='slogan_fr',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Slogan'),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='zone_intervention_en',
            field=models.CharField(default='Tout le Cameroun', max_length=200, null=True, verbose_name="Zone d'intervention"),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='zone_intervention_fr',
            field=models.CharField(default='Tout le Cameroun', max_length=200, null=True, verbose_name="Zone d'intervention"),
        ),
        migrations.AddField(
            model_name='media',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='media',
            name='description_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='media',
            name='titre_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Titre'),
        ),
        migrations.AddField(
            model_name='media',
            name='titre_fr',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Titre'),
        ),
        migrations.AddField(
            model_name='realisation',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='realisation',
            name='description_fr',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='realisation',
            name='localisation_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Localisation'),
        ),
        migrations.AddField(
            model_name='realisation',
            name='localisation_fr',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Localisation'),
        ),
        migrations.AddField(
            model_name='realisation',
            name='titre_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Titre'),
        ),
        migrations.AddField(
            model_name='realisation',
            name='titre_fr',
            field=models.CharField(max_length=200, null=True, verbose_name='Titre'),
        ),
        migrations.AddField(
            model_name='service',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='service',
            name='description_fr',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='service',
            name='titre_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Titre'),
        ),
        migrations.AddField(
            model_name='service',
            name='titre_fr',
            field=models.CharField(max_length=200, null=True, verbose_name='Titre'),
        ),
        migrations.AddField(
            model_name='valeur',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='valeur',
            name='description_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='valeur',
            name='titre_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Titre'),
        ),
        migrations.AddField(
            model_name='valeur',
            name='titre_fr',
            field=models.CharField(max_length=200, null=True, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='document',
            name='fichier',
            field=models.ImageField(upload_to='media/', verbose_name='Fichier'),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='realisation',
            name='image_principale',
            field=models.ImageField(upload_to='media/', verbose_name='Image principale'),
        ),
    ]
