# Generated by Django 6.0.3 on 2026-04-02 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eau', '0003_client'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
    ]
