# Generated by Django 6.0.3 on 2026-04-02 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eau', '0003_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=50, unique=True, verbose_name='Référence')),
                ('objet', models.CharField(help_text='Ex: Forage à Pouma', max_length=255, verbose_name='Objet du devis')),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('date_validite', models.DateField(verbose_name='Date de validité')),
                ('statut', models.CharField(choices=[('envoye', 'Envoyé'), ('accepte', 'Accepté'), ('refuse', 'Refusé')], default='envoye', max_length=20)),
                ('total_ht', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devis', to='eau.client')),
            ],
            options={
                'verbose_name': 'Devis',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='LigneDevis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(blank=True, max_length=100, verbose_name='Section')),
                ('designation', models.CharField(max_length=255, verbose_name='Désignation')),
                ('unite', models.CharField(default='ff', max_length=20, verbose_name='Unité')),
                ('prix_unitaire', models.DecimalField(decimal_places=0, max_digits=12)),
                ('quantite', models.FloatField(default=1)),
                ('devis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='devis.devis')),
            ],
            options={
                'verbose_name': 'Ligne de devis',
            },
        ),
    ]
