# Generated by Django 6.0.3 on 2026-04-02 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lignedevis',
            name='devis',
        ),
        migrations.AlterField(
            model_name='devis',
            name='objet',
            field=models.CharField(max_length=255, verbose_name='Objet'),
        ),
        migrations.AlterField(
            model_name='devis',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('envoye', 'Envoyé'), ('accepte', 'Accepté'), ('refuse', 'Refusé')], default='brouillon', max_length=20),
        ),
        migrations.CreateModel(
            name='SectionDevis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255, verbose_name='Titre de la section')),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('devis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='devis.devis')),
            ],
            options={
                'verbose_name': 'Section de devis',
                'ordering': ['ordre'],
            },
        ),
        migrations.AlterField(
            model_name='lignedevis',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='devis.sectiondevis'),
        ),
    ]
