# Generated by Django 6.0.3 on 2026-04-02 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0003_client_alter_devis_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devis',
            name='statut',
            field=models.CharField(choices=[('envoye', 'Envoyé'), ('accepte', 'Accepté'), ('refuse', 'Refusé')], default='envoye', max_length=20),
        ),
        migrations.AlterField(
            model_name='lignedevis',
            name='quantite',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
    ]
