# Generated by Django 6.0.3 on 2026-04-02 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0004_alter_devis_statut_alter_lignedevis_quantite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lignedevis',
            name='prix_unitaire',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
