# Generated by Django 6.0.3 on 2026-04-04 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0005_alter_lignedevis_prix_unitaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Adresse email'),
        ),
    ]
