# Generated by Django 6.0.3 on 2026-04-03 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devis', '0005_alter_lignedevis_prix_unitaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=50, unique=True, verbose_name='Référence')),
                ('titre', models.CharField(max_length=255, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description détaillée')),
                ('type_maintenance', models.CharField(choices=[('preventive', 'Maintenance préventive'), ('corrective', 'Maintenance corrective'), ('urgente', 'Maintenance urgente')], default='preventive', max_length=20, verbose_name='Type')),
                ('statut', models.CharField(choices=[('planifiee', 'Planifiée'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='planifiee', max_length=20, verbose_name='Statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_maintenance', models.DateTimeField(verbose_name='Date de la maintenance')),
                ('duree_estimee', models.DurationField(blank=True, help_text='Durée estimée (HH:MM:SS)', null=True, verbose_name='Durée estimée')),
                ('lieu', models.CharField(max_length=255, verbose_name="Lieu d'intervention")),
                ('actions_a_realiser', models.TextField(verbose_name='Actions à réaliser')),
                ('notification_envoyee_client', models.BooleanField(default=False, verbose_name='Notification client envoyée')),
                ('notification_envoyee_admin', models.BooleanField(default=False, verbose_name='Notification admin envoyée')),
                ('rappel_envoye', models.BooleanField(default=False, verbose_name='Rappel envoyé')),
                ('date_notification', models.DateTimeField(blank=True, null=True, verbose_name='Date notification')),
                ('date_rappel', models.DateTimeField(blank=True, null=True, verbose_name='Date rappel')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='devis.client')),
            ],
            options={
                'verbose_name': 'Maintenance',
                'verbose_name_plural': 'Maintenances',
                'ordering': ['-date_maintenance'],
                'indexes': [models.Index(fields=['date_maintenance', 'statut'], name='maintenance_date_ma_d2737a_idx'), models.Index(fields=['client'], name='maintenance_client__a9a411_idx')],
            },
        ),
    ]
